In [4]:
import pandas as pd

In [26]:
df_visits = pd.read_csv("data/raw/Demo Hospital Outpatient Data_NHC.csv")
df_visits

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration,Nursing,Laboratory,Consultation,Pharmacy
0,2020-05-06,688923,68,Female,Diabetes,True,20006,2274.0,33,105,101,28,112
1,2018-08-04,886361,62,Female,Urinary Tract Infection,False,20005,3430.0,46,75,84,102,36
2,2021-04-10,464823,70,Female,Upper Respiratory Tract Infection,True,10003,1836.0,107,81,5,77,36
3,2021-10-01,655214,8,Female,Upper Respiratory Tract Infection,False,10006,3250.0,66,31,101,35,92
4,2018-04-30,454666,24,Male,Malaria,True,10006,2262.0,68,55,60,90,104
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,2018-09-30,385435,9,Male,Abdominal pain,True,10004,1458.0,80,52,11,42,58
999996,2020-05-08,117261,29,Female,Urinary Tract Infection,True,20009,1836.0,59,57,64,66,60
999997,2019-12-31,594613,39,Female,Upper Respiratory Tract Infection,False,10001,1930.0,10,14,69,14,86
999998,2019-11-04,152179,39,Female,Malaria,False,20006,3950.0,119,52,60,94,70
999999,2019-05-11,370584,76,Female,Malaria,False,20012,3500.0,34,90,29,97,100

In [28]:
df_visits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 13 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   Visit_Date     1000000 non-null  object
 1   Patient_ID     1000000 non-null  int64
 2   Age            1000000 non-null  int64
 3   Gender         1000000 non-null  object
 4   Diagnosis      1000000 non-null  object
 5   Has_Insurance  1000000 non-null  bool
 6   Postcode       1000000 non-null  int64
 7   Total_Cost     1000000 non-null  float64
 8   Registration   1000000 non-null  int64
 9   Nursing        1000000 non-null  int64
 10  Laboratory     1000000 non-null  int64
 11  Consultation   1000000 non-null  int64
 12  Pharmacy       1000000 non-null  int64
dtypes: bool(1), float64(1), int64(8), object(3)
memory usage: 92.5+ MB

In [30]:
df_visits.isna()

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration,Nursing,Laboratory,Consultation,Pharmacy
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,False,False,False,False,False,False,False,False,False,False,False,False,False
999996,False,False,False,False,False,False,False,False,False,False,False,False,False
999997,False,False,False,False,False,False,False,False,False,False,False,False,False
999998,False,False,False,False,False,False,False,False,False,False,False,False,False
999999,False,False,False,False,False,False,False,False,False,False,False,False,False

In [32]:
df_visits.isna().sum()

Visit_Date       0
Patient_ID       0
Age              0
Gender           0
Diagnosis        0
Has_Insurance    0
Postcode         0
Total_Cost       0
Registration     0
Nursing          0
Laboratory       0
Consultation     0
Pharmacy         0
dtype: int64

In [34]:
df_visits.dropna()

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration,Nursing,Laboratory,Consultation,Pharmacy
0,2020-05-06,688923,68,Female,Diabetes,True,20006,2274.0,33,105,101,28,112
1,2018-08-04,886361,62,Female,Urinary Tract Infection,False,20005,3430.0,46,75,84,102,36
2,2021-04-10,464823,70,Female,Upper Respiratory Tract Infection,True,10003,1836.0,107,81,5,77,36
3,2021-10-01,655214,8,Female,Upper Respiratory Tract Infection,False,10006,3250.0,66,31,101,35,92
4,2018-04-30,454666,24,Male,Malaria,True,10006,2262.0,68,55,60,90,104
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,2018-09-30,385435,9,Male,Abdominal pain,True,10004,1458.0,80,52,11,42,58
999996,2020-05-08,117261,29,Female,Urinary Tract Infection,True,20009,1836.0,59,57,64,66,60
999997,2019-12-31,594613,39,Female,Upper Respiratory Tract Infection,False,10001,1930.0,10,14,69,14,86
999998,2019-11-04,152179,39,Female,Malaria,False,20006,3950.0,119,52,60,94,70
999999,2019-05-11,370584,76,Female,Malaria,False,20012,3500.0,34,90,29,97,100

In [36]:
df_visits = df_visits.dropna()
df_visits.sample(n=5)

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration,Nursing,Laboratory,Consultation,Pharmacy
250695,2020-05-12,651431,30,Female,Upper Respiratory Tract Infection,False,10004,3030.0,46,89,22,48,98
334299,2019-12-11,528454,2,Male,Abdominal pain,False,10014,2410.0,58,15,85,44,39
964250,2020-10-18,909064,26,Male,Backpain,True,10004,2748.0,120,65,108,77,88
869341,2018-04-11,486650,50,Male,Urinary Tract Infection,False,10008,4480.0,102,101,89,91,65
257520,2021-02-23,647490,28,Male,Backpain,True,20004,2184.0,94,5,114,60,91

In [38]:
df_visits.rename(columns={'Registration': 'Registration_minutes'})

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration_minutes,Nursing,Laboratory,Consultation,Pharmacy
0,2020-05-06,688923,68,Female,Diabetes,True,20006,2274.0,33,105,101,28,112
1,2018-08-04,886361,62,Female,Urinary Tract Infection,False,20005,3430.0,46,75,84,102,36
2,2021-04-10,464823,70,Female,Upper Respiratory Tract Infection,True,10003,1836.0,107,81,5,77,36
3,2021-10-01,655214,8,Female,Upper Respiratory Tract Infection,False,10006,3250.0,66,31,101,35,92
4,2018-04-30,454666,24,Male,Malaria,True,10006,2262.0,68,55,60,90,104
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,2018-09-30,385435,9,Male,Abdominal pain,True,10004,1458.0,80,52,11,42,58
999996,2020-05-08,117261,29,Female,Urinary Tract Infection,True,20009,1836.0,59,57,64,66,60
999997,2019-12-31,594613,39,Female,Upper Respiratory Tract Infection,False,10001,1930.0,10,14,69,14,86
999998,2019-11-04,152179,39,Female,Malaria,False,20006,3950.0,119,52,60,94,70
999999,2019-05-11,370584,76,Female,Malaria,False,20012,3500.0,34,90,29,97,100

In [40]:
df_visits.rename(columns={'Registration': 'Registration_minutes'}, inplace=True)

In [42]:
df_visits

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration_minutes,Nursing,Laboratory,Consultation,Pharmacy
0,2020-05-06,688923,68,Female,Diabetes,True,20006,2274.0,33,105,101,28,112
1,2018-08-04,886361,62,Female,Urinary Tract Infection,False,20005,3430.0,46,75,84,102,36
2,2021-04-10,464823,70,Female,Upper Respiratory Tract Infection,True,10003,1836.0,107,81,5,77,36
3,2021-10-01,655214,8,Female,Upper Respiratory Tract Infection,False,10006,3250.0,66,31,101,35,92
4,2018-04-30,454666,24,Male,Malaria,True,10006,2262.0,68,55,60,90,104
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,2018-09-30,385435,9,Male,Abdominal pain,True,10004,1458.0,80,52,11,42,58
999996,2020-05-08,117261,29,Female,Urinary Tract Infection,True,20009,1836.0,59,57,64,66,60
999997,2019-12-31,594613,39,Female,Upper Respiratory Tract Infection,False,10001,1930.0,10,14,69,14,86
999998,2019-11-04,152179,39,Female,Malaria,False,20006,3950.0,119,52,60,94,70
999999,2019-05-11,370584,76,Female,Malaria,False,20012,3500.0,34,90,29,97,100

In [48]:
column_mapping = {
    'Nursing': 'Nursing_minutes',
    'Laboratory': 'Laboratory_minutes',
    'Consultation': 'Consultation_minutes',
    'Pharmacy': 'Pharmacy_minutes'
}

In [52]:
df_visits.rename(columns=column_mapping, inplace=True)
df_visits

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration_minutes,Nursing_minutes,Laboratory_minutes,Consultation_minutes,Pharmacy_minutes
0,2020-05-06,688923,68,Female,Diabetes,True,20006,2274.0,33,105,101,28,112
1,2018-08-04,886361,62,Female,Urinary Tract Infection,False,20005,3430.0,46,75,84,102,36
2,2021-04-10,464823,70,Female,Upper Respiratory Tract Infection,True,10003,1836.0,107,81,5,77,36
3,2021-10-01,655214,8,Female,Upper Respiratory Tract Infection,False,10006,3250.0,66,31,101,35,92
4,2018-04-30,454666,24,Male,Malaria,True,10006,2262.0,68,55,60,90,104
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,2018-09-30,385435,9,Male,Abdominal pain,True,10004,1458.0,80,52,11,42,58
999996,2020-05-08,117261,29,Female,Urinary Tract Infection,True,20009,1836.0,59,57,64,66,60
999997,2019-12-31,594613,39,Female,Upper Respiratory Tract Infection,False,10001,1930.0,10,14,69,14,86
999998,2019-11-04,152179,39,Female,Malaria,False,20006,3950.0,119,52,60,94,70
999999,2019-05-11,370584,76,Female,Malaria,False,20012,3500.0,34,90,29,97,100

In [60]:
# df_visits.to_csv('data/clean/Demo Hospital Outpatient Data Clean_NHC.csv')
# index set to false to avoid unnamed indexing
df_visits.to_csv('data/clean/Demo Hospital Outpatient Data Clean_NHC.csv', index=False)

In [61]:
pd.read_csv('data/clean/Demo Hospital Outpatient Data Clean_NHC.csv')

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration_minutes,Nursing_minutes,Laboratory_minutes,Consultation_minutes,Pharmacy_minutes
0,2020-05-06,688923,68,Female,Diabetes,True,20006,2274.0,33,105,101,28,112
1,2018-08-04,886361,62,Female,Urinary Tract Infection,False,20005,3430.0,46,75,84,102,36
2,2021-04-10,464823,70,Female,Upper Respiratory Tract Infection,True,10003,1836.0,107,81,5,77,36
3,2021-10-01,655214,8,Female,Upper Respiratory Tract Infection,False,10006,3250.0,66,31,101,35,92
4,2018-04-30,454666,24,Male,Malaria,True,10006,2262.0,68,55,60,90,104
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,2018-09-30,385435,9,Male,Abdominal pain,True,10004,1458.0,80,52,11,42,58
999996,2020-05-08,117261,29,Female,Urinary Tract Infection,True,20009,1836.0,59,57,64,66,60
999997,2019-12-31,594613,39,Female,Upper Respiratory Tract Infection,False,10001,1930.0,10,14,69,14,86
999998,2019-11-04,152179,39,Female,Malaria,False,20006,3950.0,119,52,60,94,70
999999,2019-05-11,370584,76,Female,Malaria,False,20012,3500.0,34,90,29,97,100

In [64]:
df_visits.to_excel('data/clean/Demo Hospital Outpatient Data Clean_NHC.xlsx', index=False)

In [66]:
pd.read_excel('data/clean/Demo Hospital Outpatient Data Clean_NHC.xlsx')

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration_minutes,Nursing_minutes,Laboratory_minutes,Consultation_minutes,Pharmacy_minutes
0,2020-05-06,688923,68,Female,Diabetes,True,20006,2274,33,105,101,28,112
1,2018-08-04,886361,62,Female,Urinary Tract Infection,False,20005,3430,46,75,84,102,36
2,2021-04-10,464823,70,Female,Upper Respiratory Tract Infection,True,10003,1836,107,81,5,77,36
3,2021-10-01,655214,8,Female,Upper Respiratory Tract Infection,False,10006,3250,66,31,101,35,92
4,2018-04-30,454666,24,Male,Malaria,True,10006,2262,68,55,60,90,104
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,2018-09-30,385435,9,Male,Abdominal pain,True,10004,1458,80,52,11,42,58
999996,2020-05-08,117261,29,Female,Urinary Tract Infection,True,20009,1836,59,57,64,66,60
999997,2019-12-31,594613,39,Female,Upper Respiratory Tract Infection,False,10001,1930,10,14,69,14,86
999998,2019-11-04,152179,39,Female,Malaria,False,20006,3950,119,52,60,94,70
999999,2019-05-11,370584,76,Female,Malaria,False,20012,3500,34,90,29,97,100

In [67]:
import zipfile

In [70]:
zipped_file_name = 'demo_hospital_outpatient_data_clean.zip'

In [76]:
with zipfile.ZipFile(zipped_file_name, 'w', zipfile.ZIP_DEFLATED) as zip:
    zip.write('data/clean/Demo Hospital Outpatient Data Clean_NHC.csv')

In [80]:
pd.read_csv('data/clean/demo_hospital_outpatient_data_clean.zip')

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration_minutes,Nursing_minutes,Laboratory_minutes,Consultation_minutes,Pharmacy_minutes
0,2020-05-06,688923,68,Female,Diabetes,True,20006,2274.0,33,105,101,28,112
1,2018-08-04,886361,62,Female,Urinary Tract Infection,False,20005,3430.0,46,75,84,102,36
2,2021-04-10,464823,70,Female,Upper Respiratory Tract Infection,True,10003,1836.0,107,81,5,77,36
3,2021-10-01,655214,8,Female,Upper Respiratory Tract Infection,False,10006,3250.0,66,31,101,35,92
4,2018-04-30,454666,24,Male,Malaria,True,10006,2262.0,68,55,60,90,104
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,2018-09-30,385435,9,Male,Abdominal pain,True,10004,1458.0,80,52,11,42,58
999996,2020-05-08,117261,29,Female,Urinary Tract Infection,True,20009,1836.0,59,57,64,66,60
999997,2019-12-31,594613,39,Female,Upper Respiratory Tract Infection,False,10001,1930.0,10,14,69,14,86
999998,2019-11-04,152179,39,Female,Malaria,False,20006,3950.0,119,52,60,94,70
999999,2019-05-11,370584,76,Female,Malaria,False,20012,3500.0,34,90,29,97,100

In [84]:
!pip install pyreadstat

Collecting pyreadstat
  Downloading pyreadstat-1.2.8-cp312-cp312-win_amd64.whl.metadata (1.1 kB)
Requirement already satisfied: pandas>=1.2.0 in c:\users\dikhw\anaconda3\lib\site-packages (from pyreadstat) (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dikhw\anaconda3\lib\site-packages (from pandas>=1.2.0->pyreadstat) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dikhw\anaconda3\lib\site-packages (from pandas>=1.2.0->pyreadstat) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dikhw\anaconda3\lib\site-packages (from pandas>=1.2.0->pyreadstat) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dikhw\anaconda3\lib\site-packages (from pandas>=1.2.0->pyreadstat) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\dikhw\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.2.0->pyreadstat) (1.16.0)
Downloading pyreadstat-1.2.8-cp312-cp312-win_amd64.whl (2.4 MB)
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   -------- ------------------------------- 0.5/2.4 MB 5.6 MB/s eta 0:00:01
   ----------------- ---------------------- 1.0/2.4 MB 8.4 MB/s eta 0:00:01
   ---------------------------------- ----- 2.1/2.4 MB 4.3 MB/s eta 0:00:01
   ---------------------------------- ----- 2.1/2.4 MB 4.3 MB/s eta 0:00:01
   ---------------------------------------- 2.4/2.4 MB 2.9 MB/s eta 0:00:00
Installing collected packages: pyreadstat
Successfully installed pyreadstat-1.2.8

In [94]:
import pyreadstat

In [96]:
spss_file = 'demo_hospital_outpatient_data_clean.sav'

In [98]:
pyreadstat.write_sav(df_visits, spss_file)

In [100]:
data, meta = pyreadstat.read_sav('data/clean/demo_hospital_outpatient_data_clean.sav')

In [102]:
data

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration_minutes,Nursing_minutes,Laboratory_minutes,Consultation_minutes,Pharmacy_minutes
0,2020-05-06,688923.0,68.0,Female,Diabetes,1.0,20006.0,2274.0,33.0,105.0,101.0,28.0,112.0
1,2018-08-04,886361.0,62.0,Female,Urinary Tract Infection,0.0,20005.0,3430.0,46.0,75.0,84.0,102.0,36.0
2,2021-04-10,464823.0,70.0,Female,Upper Respiratory Tract Infection,1.0,10003.0,1836.0,107.0,81.0,5.0,77.0,36.0
3,2021-10-01,655214.0,8.0,Female,Upper Respiratory Tract Infection,0.0,10006.0,3250.0,66.0,31.0,101.0,35.0,92.0
4,2018-04-30,454666.0,24.0,Male,Malaria,1.0,10006.0,2262.0,68.0,55.0,60.0,90.0,104.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,2018-09-30,385435.0,9.0,Male,Abdominal pain,1.0,10004.0,1458.0,80.0,52.0,11.0,42.0,58.0
999996,2020-05-08,117261.0,29.0,Female,Urinary Tract Infection,1.0,20009.0,1836.0,59.0,57.0,64.0,66.0,60.0
999997,2019-12-31,594613.0,39.0,Female,Upper Respiratory Tract Infection,0.0,10001.0,1930.0,10.0,14.0,69.0,14.0,86.0
999998,2019-11-04,152179.0,39.0,Female,Malaria,0.0,20006.0,3950.0,119.0,52.0,60.0,94.0,70.0
999999,2019-05-11,370584.0,76.0,Female,Malaria,0.0,20012.0,3500.0,34.0,90.0,29.0,97.0,100.0

In [104]:
meta

In [106]:
df_visits = pd.DataFrame(data)